### PR TITLE
Added test to to verify correctness of periodic qos collection

### PR DESCRIPTION
**Pull request by tomaszklak**
### :ballot_box_with_check: Definition of Done checklist
- [x] Commit history is clean ([requirements](../blob/main/docs/git_commit_messages_requirements.md))
- [x] README.md is updated
- [x] Functionality is covered by unit or integration tests

### CODE REVIEW

**Comment by mathiaspeters** [comment]
I'm not entirely sure what the new test is actually testing, so it would be nice with a comment or maybe a more descriptive name

**Comment by mathiaspeters** [comment]
The name is definitely better. A last question, with the increase RTT interval we don't typically collect that data during our tests and this test sets it to something shorter and checks that it's collected as expected?

**Comment by mathiaspeters** [comment]
+1

**Comment by matszczygiel** [comment]
+1

**Pull request merged**
