### PR TITLE
PMTU tests are flaky most probably due to the nature of docker networ…

### PR DESCRIPTION
**Pull request by LukasPukenis**
This needs more investigation but for now it blocks the CI

### :ballot_box_with_check: Definition of Done checklist
- [x] Commit history is clean ([requirements](../blob/main/docs/git_commit_messages_requirements.md))
- [x] README.md is updated
- [x] changelog.md is updated
- [x] Functionality is covered by unit or integration tests

### CODE REVIEW

**Comment by matislovas** [comment]
I would vote to changing the filename to `_test_pmtu.py`. 

On the other hand, shouldn't we revert PR/commit, which introduces these tests instead ..?

**Comment by LukasPukenis** [comment]
The test should have been merged alongside the feature so reverting would mean reverting the whole thing. The flakyness which I only now observed might be due to the docker networking intricacies.

Does renaming with underscore prefix skip it?

**Comment by gytsto** [comment]
Add pytest.mark.skip("<jira ticket id for fixing test>"). It will disable test.

**Comment by matszczygiel** [comment]
@LukasPukenis does this https://github.com/NordSecurity/libtelio/pull/422 solve the problem?

**Pull request closed without merging**
