### PR TITLE
Update nordderper configs

### PR DESCRIPTION
**Pull request by stalowyjez**
Updates nordderper configs, so they are compliant with the new version of nordderper.

### Problem
New nordderper version requires updated config files.

### Solution
Update config files.

### :ballot_box_with_check: Definition of Done checklist
- [x] Commit history is clean ([requirements](../../blob/main/docs/git_commit_messages_requirements.md))
- [x] README.md is updated
- [x] changelog.md is updated

### CODE REVIEW

**Review by Jauler — APPROVED** [review]
+2.0

**Review by gytsto — COMMENTED** [review]
Add `limits` section to configs

**Review by gytsto — COMMENTED** [review]
Also dont forget to update ref to build repo

**Review by gytsto — COMMENTED** [review]
`tests/test_derp_client_message_forward.py::DERP_SERVER` and `DERP_SERVER_2` maybe needs an update also?

**Comment by stalowyjez** [comment]
@gytsto it looks that tests/test_derp_client_message_forward.py::DERP_SERVER should use the user port, which is the same as previous port, so I think we should leave it as it is. About limits - I guess default ones are ok?

**Comment by gytsto** [comment]
> @gytsto it looks that tests/test_derp_client_message_forward.py::DERP_SERVER should use the user port, which is the same as previous port, so I think we should leave it as it is. About limits - I guess default ones are ok?

Just wanted to add limits to config, so people know that there is an option of configuring it without looking at nordderper repo/source

**Review by jjanowsk — APPROVED** [review]

**Review by gytsto — APPROVED** [review]

**Pull request merged**
