### PR TITLE
LLT-4433 Bump moose version to v0.8.2

### PR DESCRIPTION
**Pull request by matislovas**

### CODE REVIEW

**Comment by lcruz99** [comment]
8d520607 commit with moose bump could be on top of `v0.1.10-tvOS` -> `v0.1.11-tvOS`, and so `--moose` flag should be included to the tvOS build.

**Comment by matislovas** [comment]
> 8d520607 commit with moose bump could be on top of `v0.1.10-tvOS` -> `v0.1.11-tvOS`, and so `--moose` flag should be included to the tvOS build.

@lcruz99  So actually `release/v4.1` was forked from `v0.1.10-tvOS` tag.

**Comment by lcruz99** [comment]
> @lcruz99 So actually `release/v4.1` was forked from `v0.1.10-tvOS` tag.

I see, so moose will not be included into tvOS build, this is only possible from `v0.10.0`.

**Comment by lcruz99** [comment]
+2

**Comment by packgron** [comment]
Why is MOOSE_VERSION const not changed in https://github.com/NordSecurity/libtelio/blob/main/crates/telio-lana/src/lib.rs#L26

**Review by packgron — CHANGES_REQUESTED** [review]
Why is MOOSE_VERSION const not changed in https://github.com/NordSecurity/libtelio/blob/main/crates/telio-lana/src/lib.rs#L26

**Comment by matislovas** [comment]
> MOOSE_VERSION

whoops, fixed

**Review by packgron — APPROVED** [review]
+2

**Pull request merged**
