### PR TITLE
natlab: Refactor event validators with decorator pattern

### PR DESCRIPTION
**Pull request by lcruz99**
Refactor [event validators](https://github.com/NordSecurity/libtelio/blob/main/nat-lab/tests/utils/analytics/event_validator.py).

[test_lana_validator.py](https://github.com/NordSecurity/libtelio/blob/main/nat-lab/tests/utils/analytics/test_lana_validator.py) also needs to be refactored, will be done in a follow-up task.

### :ballot_box_with_check: Definition of Done checklist
- [x] Commit history is clean ([requirements](../blob/main/docs/git_commit_messages_requirements.md))
- [x] README.md is updated
- [x] Functionality is covered by unit or integration tests

### CODE REVIEW

**Comment by stalowyjez** [comment]
Hmm, what is the motivation for this refactor?

**Comment by lcruz99** [comment]
> Hmm, what is the motivation for this refactor?

Mostly readability and ease-of-use. [LLT-4994]

**Review by gytsto — COMMENTED** [review]
+1

**Review by mathiaspeters — APPROVED** [review]
+1

**Pull request merged**
