### PR TITLE
LLT-4983: expose telio panic method

### PR DESCRIPTION
**Pull request by lcruz99**
### Problem
libtelio has a method `__telio_generate_stack_panic` but currently it’s not being exposed to apps.

### Solution
expose this method and generate ffi bindings.

### :ballot_box_with_check: Definition of Done checklist
- [x] Commit history is clean ([requirements](../blob/main/docs/git_commit_messages_requirements.md))
- [x] README.md is updated
- [x] changelog.md is updated
- [x] Functionality is covered by unit or integration tests

### CODE REVIEW

**Review by LukasPukenis — COMMENTED** [review]
Could you slightly elaborate why apps would need such a call? It might good to overwrite commit message to includ ethat information as well.

The code itself doesn't raise any questions

**Comment by lcruz99** [comment]
@LukasPukenis This is more of a convenience to apps team, so that they can properly test panic calls. Will add this info to the commit.

**Comment by packgron** [comment]
> Could you slightly elaborate why apps would need such a call? It might good to overwrite commit message to includ ethat information as well.
> 
> The code itself doesn't raise any questions

We have mechanizim that allows apps to react to critical failures a.k.a panics, but they cannot actually test this and see if the code they implemented actually would work in real life scenario

**Review by packgron — APPROVED** [review]
+1 don't forget backports to release/4.2 release/4.3

**Pull request merged**
