### PR TITLE
Bump to boringtun with more logs

### PR DESCRIPTION
**Pull request by packgron**
### Problem
Need a new boringtun that logs details about ioctl failures

### Solution
bumped to v1.2.2

### Notes
did quick test, now if ioctl fails we will see something like:
```
ERROR boringtun::device::tun: 105: Failed to configure tunnel error=IOCtl(Os { code: 22, kind: InvalidInput, message: "Invalid argument" }) op="TUNSETIFF" name="pna_beta" flags="1101"
```

### :ballot_box_with_check: Definition of Done checklist
- [x] Commit history is clean ([requirements](../blob/main/docs/git_commit_messages_requirements.md))
- [x] README.md is updated
- [x] Functionality is covered by unit or integration tests

### CODE REVIEW

**Comment by matislovas** [comment]
+2

**Review by matislovas — DISMISSED** [review]

**Review by tomasz-grz — APPROVED** [review]
+1.0

**Review by gytsto — APPROVED** [review]
+2

**Review by Jauler — APPROVED** [review]
+2.0

**Pull request merged**
