### PR TITLE
Prepare v4.2.5

### PR DESCRIPTION
**Pull request by packgron**
Prepartion for release, backports of:
* LLT-4850: Add missing VPN meshnet address to analytics
* LLT-4917: Fix the issue with wireguard-go failing to bind to a port on some devices
* LLT-4406: Implement error handling for proxy egress
* LLT-4980: Introduce synchronization for the endpoint map in telio-proxy

### :ballot_box_with_check: Definition of Done checklist
- [x] Commit history is clean ([requirements](../blob/main/docs/git_commit_messages_requirements.md))
- [x] README.md is updated
- [x] changelog.md is updated
- [x] Functionality is covered by unit or integration tests

### CODE REVIEW

**Comment by gytsto** [comment]
0.5 :shrug:

**Comment by mathiaspeters** [comment]
My changes are all there. +0.5

**Comment by jjanowsk** [comment]
+5 from my side

**Review by Jauler — APPROVED** [review]
+1.0

**Pull request merged**
