### PR TITLE
LLT-5324 Bump boringtun to v1.1.13

### PR DESCRIPTION
**Pull request by matislovas**
Backport https://github.com/NordSecurity/libtelio/pull/673

### :ballot_box_with_check: Definition of Done checklist
- [x] Commit history is clean ([requirements](../blob/main/docs/git_commit_messages_requirements.md))
- [x] README.md is updated
- [x] changelog.md is updated
- [x] Functionality is covered by unit or integration tests

### CODE REVIEW

**Comment by stalowyjez** [comment]
If you bump boringtun version anyway, maybe it would be better to use `v1.2.2` also here?

**Comment by matislovas** [comment]
> If you bump boringtun version anyway, maybe it would be better to use `v1.2.2` also here?

That makes some sense, but we do not have any data of boringtun v0.6.0 perfromance in the field, so my call would be to leave the `release/v4.3` with v0.5.2  boringtun, and let Apple team to update to telio-v5.0.0 to get v0.6.0 boringtun. But I think it is worth discussing this ...

**Comment by matislovas** [comment]
So it was decided  to stick with `v0.5.2 boringtun` on `release/v4.3`

**Review by dfetti — COMMENTED** [review]
+1.0

**Review by stalowyjez — APPROVED** [review]
+1

**Review by Jauler — APPROVED** [review]
+1.0

**Pull request merged**
